import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class HeroService {

  goalkeepers: (any)[] = [
    {
      id: 1,
      name: 'David De Gea',
      description: 'I donot know who is the best goalkeeper in the world at the moment, but I want to be the best.',
      backnumber: '1',
      position: 'First Choice Goalkeeper',
      age: '32',
      country: '🇪🇸 Spain',
      birthdate: '7 Nov 1990',
      joindate: '29 Jun 2011',
      img_url: '../assets/images/dg.png',
      debutdate: '7 Aug 2011',
    },
    {
      id: 2,
      name: 'Tom Heaton',
      description: 'I still feel I’ve got an awful lot to give and I’ve got the bit between my teeth.',
      backnumber: '22',
      position: 'Second Choice Goalkeeper',
      age: '37',
      country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England',
      birthdate: '15 Apr 1986',
      joindate: '2 Jul 2021',
      img_url: '../assets/images/th.png',
      debutdate: '-',

    },
    {
      id: 3,
      name: 'Dean Henderson',
      description: 'I work hard every single day to be a better version of myself. At the end of the day, the only competition I’ve got is myself.',
      backnumber: '26',
      position: 'Loan Keeper',
      age: '26',
      country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England',
      birthdate: '12 Mar 1997',
      joindate: '1 Aug 2013',
      img_url: '../assets/images/dh.png',
      debutdate: '-',

    }
  ]

  defenders: (any)[] = [
    {
      id: 1,
      name: 'Victor Lindelof',
      description: 'United are one of the biggest clubs in the world and always want to win titles. That’s also my goal.',
      backnumber: '2',
      position: 'Defender',
      age: '28',
      country: '🇸🇪 Sweden',
      birthdate: '17 Jul 1994',
      joindate: '1 Jul 2017',
      img_url: '../assets/images/vtldl.png',
      debutdate: '8 Aug 2017',
    },
    {
      id: 2,
      name: 'Lisandro Martinez',
      description: 'I’ve worked so hard to get to this moment and, now that I’m here, I’m going to push myself even further.',
      backnumber: '6',
      position: 'Defender',
      age: '25',
      country: '🇦🇷 Argentina',
      birthdate: '18 Jan 1998',
      joindate: '27 Jul 2022',
      img_url: '../assets/images/lsdmtn.png',
      debutdate: '7 Aug 2022',
    },
    {
      id: 3,
      name: 'Harry Maguire',
      description: 'It is an amazing club. It is a club I have always watched and I always looked up to when I was younger.',
      backnumber: '5',
      position: 'Defender',
      age: '30',
      country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England',
      birthdate: '5 Mar 1993',
      joindate: '5 Aug 2019',
      img_url: '../assets/images/hmg.png',
      debutdate: '11 Aug 2019',
    },
    {
      id: 4,
      name: 'Tyrell Malacia',
      description: 'Whilst I know that I am still young and will continue to develop, I can promise the United fans that I will leave everything on the pitch every time I pull on the red shirt.',
      backnumber: '12',
      position: 'Defender',
      age: '-',
      country: '🇳🇱 Dutch',
      birthdate: '',
      joindate: '5 Jul 2022',
      img_url: '../assets/images/trml.png',
      debutdate: '-',
    },
    {
      id: 5,
      name: 'Raphael Varane',
      description: 'I came here because I wanted new emotions and it was exactly what I expected and bigger.',
      backnumber: '19',
      position: 'Defender',
      age: '30',
      country: '🇫🇷 French',
      birthdate: '25 Apr 1993',
      joindate: '14 Aug 2021',
      img_url: '../assets/images/rpvr.png',
      debutdate: '-',
    },
    {
      id: 6,
      name: 'Diogo Dalot',
      description: 'I will give everything for this club, for this shirt and, hopefully, help the club to win. That’s the most important thing.',
      backnumber: '20',
      position: 'Defender',
      age: '24',
      country: '🇵🇹 Portugal',
      birthdate: '18 Mar 1999',
      joindate: '6 Jun 2018',
      img_url: '../assets/images/dgdl.png',
      debutdate: '-',
    },
    {
      id: 7,
      name: 'Luke Shaw',
      description: 'I’ve got the freedom to play and that gives me the confidence in what I want to do to help the team.',
      backnumber: '23',
      position: 'Defender',
      age: '27',
      country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England',
      birthdate: '12 Jul 1995',
      joindate: '27 Jul 2014',
      img_url: '../assets/images/lksw.png',
      debutdate: '27 sep 2014',
    },
    {
      id: 8,
      name: 'Aaron Wan-Bissaka',
      description: 'Every kid wants to play for a team like this. It is an honour to represent this club.',
      backnumber: '29',
      position: 'Defender',
      age: '25',
      country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England',
      birthdate: '26 Nov 1997',
      joindate: '29 Jun 2019',
      img_url: '../assets/images/arwbsk.png',
      debutdate: '11 Aug 2019',
    },
    {
      id: 9,
      name: 'Brandon Williams',
      description: 'I think the modern full-back is an attacker as well. I like attacking. I like defending. I love getting up and down.',
      backnumber: '33',
      position: 'LoanPlayer',
      age: '22',
      country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England',
      birthdate: '3 Sep 2000',
      joindate: '1 Jul 2017',
      img_url: '../assets/images/bdwl.png',
      debutdate: '25 Sep 2019',
    },
    
  ]

  midfielders: (any)[] = [
    {
      id: 1,
      name: 'Bruno Fernandes',
      description: 'To play for United feels incredible. I can promise the fans I will give everything to help bring us success.',
      backnumber: '8',
      position: 'Midfielder',
      age: '28',
      country: '🇵🇹 Portugal',
      birthdate: '8 Sep 1994',
      joindate: '30 Jan 2020',
      img_url: '../assets/images/burno.png',
      debutdate: '1 Feb 2020',
    },
    {
      id: 2,
      name: 'Christian Eriksen',
      description: 'It feels good to be here. It is very special.',
      backnumber: '14',
      position: 'Midfielder',
      age: '31',
      country: '🇩🇰 Denmark',
      birthdate: '14 Feb 1992',
      joindate: '15 Jul 2022',
      img_url: '../assets/images/eriksen.png',
      debutdate: '7 Aug 2022',
    },
    {
      id: 3,
      name: 'Fred',
      description: 'I will never forget how I felt the day I made my debut at Old Trafford. It was just fantastic.',
      backnumber: '17',
      position: 'Midfielder',
      age: '30',
      country: '🇧🇷 Brazil',
      birthdate: '5 Mar 1993',
      joindate: '21 Jun 2018',
      img_url: '../assets/images/fred.png',
      debutdate: '-',
    },
    {
      id: 4,
      name: 'Casemiro',
      description: 'To represent United is an honour and I am ready to give everything to help the team achieve our ambitions.',
      backnumber: '18',
      position: 'Midfielder',
      age: '31',
      country: '🇧🇷 Brazil',
      birthdate: '23 Feb 1992',
      joindate: '23 Feb 1992',
      img_url: '../assets/images/csmir.png',
      debutdate: '27 Aug 2022',
    },
    {
      id: 5,
      name: 'Facundo Pellistri',
      description: '',
      backnumber: '28',
      position: 'Midfielder',
      age: '21',
      country: '🇺🇾 Uruguay',
      birthdate: '20 Dec 2001',
      joindate: '5 Oct 2020',
      img_url: '../assets/images/plst.png',
      debutdate: '',
    },
    {
      id: 6,
      name: 'Scott Mctominay',
      description: 'You have got to keep working hard. The moment you stop is when things can go bad for you.',
      backnumber: '39',
      position: 'Midfielder',
      age: '26',
      country: '🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scotland',
      birthdate: '8 Dec 1996',
      joindate: '1 Jul 2012',
      img_url: '../assets/images/scmc.png',
      debutdate: '7 May 2017',
    },
    {
      id: 7,
      name: 'Donny Van De Beek',
      description: 'I am ready to take the next step in my career and there is no higher standard than Manchester United.',
      backnumber: '34',
      position: 'Midfielder',
      age: '26',
      country: '🇳🇱 Dutch',
      birthdate: '18 Apr 1997',
      joindate: '18 Apr 1997',
      img_url: '../assets/images/dnvdb.png',
      debutdate: '',
    },
    {
      id: 8,
      name: 'Kobbie Mainoo',
      description: '',
      backnumber: '73',
      position: 'Midfielder',
      age: '18',
      country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England',
      birthdate: '19 Apr 2005',
      joindate: '1 Jul 2021',
      img_url: '../assets/images/kbmn.png',
      debutdate: '',
    },
  ]

  strikers: (any)[] = [
    {
      id: 1,
      name: 'Anthony Martial',
      description: 'I love Manchester United, I love the fans, they give me a lot of joy.',
      backnumber: '9',
      position: 'ST',
      age: '27',
      country: '🇫🇷 French',
      birthdate: '5 Dec 1995',
      joindate: '1 Sep 2015',
      img_url: '../assets/images/martial.png',
      debutdate: '12 Sep 2015',
    },
    {
      id: 2,
      name: 'Marcus Rashford',
      description: 'I have always been a United fan, so to be playing in the first team really is a dream come true.',
      backnumber: '10',
      position: 'ST,LW,RW',
      age: '25',
      country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England',
      birthdate: '31 Oct 1997',
      joindate: '1 Jul 2014',
      img_url: '../assets/images/rashy.png',
      debutdate: '25 Feb 2016',
    },
    {
      id: 3,
      name: 'Mason Greenwood',
      description: '-',
      backnumber: '11',
      position: 'ST,RW',
      age: '21',
      country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England',
      birthdate: '1 Oct 2001',
      joindate: '1 Jul 2018',
      img_url: '../assets/images/greenwood.png',
      debutdate: '6 Mar 2019',
    },
    {
      id: 4,
      name: 'Antony',
      description: 'In Antony, Manchester United have a dynamic winger who can light up the right-hand side of our attack.',
      backnumber: '21',
      position: 'RW',
      age: '23',
      country: '🇧🇷 Brazil',
      birthdate: '24 Feb 2000',
      joindate: '1 Sep 2022',
      img_url: '../assets/images/antonny.png',
      debutdate: '4 Sep 2022',
    },
    {
      id: 5,
      name: 'Jadon Sancho',
      description: 'Growing up, United was one of the biggest clubs that everyone knows. So I am very happy to be wearing this jersey now.',
      backnumber: '25',
      position: 'AMF,RW',
      age: '23',
      country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England',
      birthdate: '25 Mar 2000',
      joindate: '23 Jul 2021',
      img_url: '../assets/images/sancho.png',
      debutdate: '-',
    },
    {
      id: 6,
      name: 'Anthony Elanga',
      description: '',
      backnumber: '36',
      position: 'SS',
      age: '21',
      country: '🇸🇪 Sweden',
      birthdate: '27 Apr 2002',
      joindate: '1 Jul 2018',
      img_url: '../assets/images/elanga.png',
      debutdate: '11 May 2021',
    },
    {
      id: 7,
      name: 'Alejandro Garnacho',
      description: '',
      backnumber: '49',
      position: 'LW',
      age: '18',
      country: '🇦🇷 Argentina',
      birthdate: '1 Jul 2004',
      joindate: '11 Sep 2020',
      img_url: '../assets/images/garnacho.png',
      debutdate: '',
    },
    {
      id: 8,
      name: 'Shola Shoretire',
      description: '',
      backnumber: '47',
      position: 'ST',
      age: '19',
      country: '🏴󠁧󠁢󠁥󠁮󠁧󠁿 England',
      birthdate: '2 Feb 2004',
      joindate: '1 Jul 2020',
      img_url: '../assets/images/shola.png',
      debutdate: '21 Feb 2021',
    }
  ]



  constructor() { }
}
